server:
  port: 8094
  error:
    include-message: always
    include-binding-errors: always
spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/productoDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comment: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
# Feign and Hystrix
Feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

